
export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS';
export const ON_SIGNUP = 'ON_SIGNUP';
export const ON_FORGOT_PASSWORD = 'ON_FORGOT_PASSWORD';
export const ON_FORGOT_PASSWORD_SUCCESS = 'ON_FORGOT_PASSWORD_SUCCESS';
export const ON_VERIFICATION_CODE_SUBMIT = 'ON_VERIFICATION_CODE_SUBMIT';
export const ON_RESEND_VERIFICATION_CODE = 'ON_RESEND_VERIFICATION_CODE';
export const ON_RESET_PASSWORD = 'ON_RESET_PASSWORD';
